function WormData = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WORMDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  WORMDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  WormData = importfile("C:\Users\Byron\Desktop\2020-1\2021-2\Machine Learning\ProyectoDL\WormData.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jan-2022 18:26:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["File", "Status"];
opts.VariableTypes = ["string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "File", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["File", "Status"], "EmptyFieldRule", "auto");

% Import the data
WormData = readtable(filename, opts);

end